In [5]:
import numpy as np

۱. ایجاد و مدیریت آرایهها
np.array(): ساخت آرایه از دادههای موجود.

In [17]:
image_data = [[0.1, 0.3], [0.5, 0.9]]
image_array = np.array(image_data, dtype=np.float32)
print(image_data)
print('')
print(image_array)

[[0.1, 0.3], [0.5, 0.9]]

[[0.1 0.3]
 [0.5 0.9]]


np.zeros() / np.ones(): ایجاد آرایه پر از صفر یا یک.

In [19]:
mask = np.zeros((64, 64), dtype=np.uint8)  # ماسک برای کراپ تصویر
print(mask)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


np.arange(): ایجاد آرایه با اعداد متوالی.

In [21]:
x_coords = np.arange(0, 256)  # محور X برای تبدیلات
print(x_coords)

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233
 234 235 236 237 238 239 240 241 242 243 244 245 24

۲. تغییر شکل و ابعاد آرایه
.reshape(): تغییر ابعاد آرایه بدون تغییر داده.

In [23]:
flattened_image = image_array.reshape(-1)  # تبدیل تصویر به وکتور
print(flattened_image)

[0.1 0.3 0.5 0.9]


np.transpose(): جابجایی محورها (مثلاً برای تبدیل HWC به CHW).

In [27]:
image_transposed = np.transpose(image_array, (2, 0, 1))  # مناسب برای PyTorch


ValueError: axes don't match array

np.expand_dims(): افزودن یک بعد جدید.

In [31]:
batch_image = np.expand_dims(image_array, axis=0)  # تبدیل به بچ سایز ۱
print(batch_image)

[[[0.1 0.3]
  [0.5 0.9]]]


۳. عملیات ریاضی
np.dot(): ضرب ماتریسی/دات پروداکت.

In [39]:
kernel = np.array([[1, 0], [0, -1]])
filtered = np.dot(NewModel001_New001, kernel)  # برای فیلترگذاری دستی
print(filtered)

NameError: name 'NewModel001_New001' is not defined

np.sum() / np.mean(): جمع/میانگین عناصر.

In [41]:
image_mean = np.mean(image_array)  # نرمالایز کردن روشنایی


np.clip(): محدود کردن مقادیر بین دو عدد.

In [43]:
normalized = np.clip(image_array * 255, 0, 255).astype(np.uint8)

۴. برش، الحاق و تقسیم
Slicing: برش تصویر به پچ‌های کوچک.

In [46]:
patch = image_array[10:30, 20:40]  # برش پچ ۲۰x۲۰

np.concatenate(): الحاق آرایه‌ها در یک محور.

In [49]:
combined = np.concatenate([image1, image2], axis=1)  # ترکیب افقی

NameError: name 'image1' is not defined

np.split(): تقسیم آرایه به بخش‌های کوچکتر.

In [52]:
patches = np.split(image_array, 4, axis=0)  # تقسیم به ۴ بلوک عمودی

ValueError: array split does not result in an equal division

۵. محاسبات پیشرفته
np.fft.fft2() / np.fft.ifft2(): تبدیل فوریه دو بعدی.

In [55]:
fft_image = np.fft.fft2(image_array)
reconstructed = np.fft.ifft2(fft_image).real

np.where(): اعمال شرط روی آرایه.

In [58]:
high_intensity = np.where(image_array > 0.8, 1, 0)  # شناسایی نقاط پرنور

np.linalg.norm(): محاسبه نرم (برای محاسبه Loss مثل MSE).

In [61]:
mse_loss = np.linalg.norm(original - reconstructed) ** 2

NameError: name 'original' is not defined

۶. بهینه‌سازی و محاسبات برداری
np.vectorize(): تبدیل تابع به نسخه برداری.

In [64]:
def relu(x): return max(0, x)
vectorized_relu = np.vectorize(relu)
activated = vectorized_relu(image_array)

np.einsum(): محاسبات پیشرفته برداری (مثلاً برای Attention).

In [67]:
similarity = np.einsum('hwc,dc->hwd', features, weights)

NameError: name 'features' is not defined

۷. توابع کاربردی برای فراوضوح
np.lib.stride_tricks.sliding_window_view(): ساخت پچ‌های متوالی.

In [70]:
patches = np.lib.stride_tricks.sliding_window_view(image, (32, 32))

NameError: name 'image' is not defined

np.pad(): اضافه کردن حاشیه به تصویر.

In [73]:
padded = np.pad(image, ((10,10), (10,10)), mode='reflect')  # مناسب برای کانولوشن

NameError: name 'image' is not defined

np.meshgrid(): ایجاد شبکه مختصات (برای Warping).

In [76]:
x, y = np.meshgrid(np.arange(256), np.arange(256))

مثال جامع: محاسبه PSNR

def calculate_psnr(original, reconstructed):
    mse = np.mean((original - reconstructed) ** 2)
    max_pixel = 1.0  # اگر تصویر نرمالایز شده است
    psnr = 20 * np.log10(max_pixel / np.sqrt(mse))
    return psnr